### ISSUE TITLE
Add Support for non-LTS and dev/beta ubuntu versions

### ISSUE THREAD

**Issue by human-being-1** [ubports/unity8#106]
Currently,
`bash <(wget -qO- https://raw.githubusercontent.com/ubports/unity8-desktop-install-tools/master/install.sh)`
returns:
`This is only supported on Ubuntu xenial and bionic`
I am on Ubuntu Disco Dingo Dev Branch

**Comment by UniversalSuperBox** [comment]
Hello @NanhuGITHUB,

We are currently not building Unity8 for other releases of Ubuntu. This is unlikely to change until Unity8 has been stabilized on an LTS, the UBports phone images are using the newest version, and we have a better packaging infrastructure which can handle changes in upstream releases of Ubuntu properly.

**Comment by human-being-1** [comment]
Ok. I will wait. My KDE Plasma looks just like unity so I can wait.

**Comment by UniversalSuperBox** [comment]
I believe this issue was filed regarding a unity8 desktop installer. We are not currently able to offer support for this... We may release more proper desktop installers with our transition of Ubuntu Touch to Ubuntu 20.04, or another distribution may provide proper images with Lomiri.

Either way, I believe this issue should be closed since this revision of the project is essentially dropped. Lomiri will still come back to the desktop, but not using unity8-desktop-install-tools.
