### ISSUE TITLE
unity 8 crash on ubuntu 18.04

### ISSUE THREAD

**Issue by MohsenNz** [ubports/unity8#149]
hi. when i try to run an app , unity 8 crash.
OS: Ubuntu 18.04

**Comment by dobey** [comment]
Why don't you start working on this issue then? Solving the more complex problems are going to be very difficult when nothing works. I'd suggest an ssh session into the VM and attaching to the running unity8, and trying to get a useful stack trace.

**Comment by MohsenNz** [comment]
Ty. I try it sure. and i will ask my problems here.

**Comment by MohsenNz** [comment]
now i have access to unity 8 via ssh. should i use gdb to stack trace?
if yes, how?I need a reference to learn it.

**Comment by UniversalSuperBox** [comment]
I believe this issue was filed regarding a unity8 desktop installer. We are not currently able to offer support for this... We may release more proper desktop installers with our transition of Ubuntu Touch to Ubuntu 20.04, or another distribution may provide proper images with Lomiri.

Either way, I believe this issue should be closed since this revision of the project is essentially dropped. Lomiri will still come back to the desktop, but not using unity8-desktop-install-tools.
