### ISSUE TITLE
Move USC and QtMir to Miral

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/unity8#17]
Look into what Yunit has started for this: https://github.com/yunit-io/unity-system-compositor/issues/1

**Comment by WebDrake** [comment]
Now some work-in-progress for UBPorts: https://github.com/ubports/unity-system-compositor/pull/4

I can also take a look into what might be needed on the QtMir side of things, although no promises about when.

**Comment by UniversalSuperBox** [comment]
I believe this issue is now at-best out of date and at-worst incorrect.

We were able to base Unity System Compositor and QtMir on Mir up to and including 1.8 due to the Mir team including the mirclient APIs in these production releases of Mir.

Much of the code inside QtMir which depended directly on Mir was also moved into a `miral` platform within QtMir.

However, after Mir 2.0, mirclient was removed. With much of the work to make MirAL happen stalled, Alan started the Miroil project to help.

https://forums.ubports.com/topic/5222/introducing-miroil

https://forums.ubports.com/topic/5822/miroil-for-lomiri

The work that was originally to be MirAL is now Miroil. You can learn more about the Miroil project from the UBports forum.
