### ISSUE TITLE
Error installing unity8 on VBox(Versión 5.1.38_Ubuntu r122592) with Xenial

### ISSUE THREAD

**Issue by dlagg** [ubports/unity8#171]
using 4.15.0-54-generic #58~16.04.1-Ubuntu

When I try to run this:
 `bash <(wget -qO- https://raw.githubusercontent.com/ubports/unity8-desktop-install-tools/master/install.sh)
` 
from [here](https://github.com/ubports/unity8/#how-to-install)
I get a dependency problem with:
`unity8-desktop-session (depending)--> unity8`
I did apt dist-upgrade because I have a lot of retained packages.
And I try apt install unity8, but I still having dependencies problems:
`unity8 (depending)--> unity-launcher-impl-13 , unity8-common , unity8-private
`
What am I missing? thanks a lot!

**Comment by GizmoChicken** [comment]
Problems installing Unity8 on Xenial are known.  See Issue #64 

Currently, you can install Unity8 on Bionic, but not much is working as of now.
 
Like you, I'm eager to have Unity8 working on the desktop.  My thinking is that many will want to try Unity8 on the desktop _first_, and if they like what they see on the desktop, they'll be more likely to install UT on a phone.

Hopefully the devs will allocate more resources to developing Unity8 for the desktop once the [upgrade to Unity8/Mir](https://github.com/orgs/ubports/projects/10) has been pushed to stable branch for the phone.

**Comment by UniversalSuperBox** [comment]
I believe this issue was filed regarding a unity8 desktop installer. We are not currently able to offer support for this... We may release more proper desktop installers with our transition of Ubuntu Touch to Ubuntu 20.04, or another distribution may provide proper images with Lomiri.

Either way, I believe this issue should be closed since this revision of the project is essentially dropped. Lomiri will still come back to the desktop, but not using unity8-desktop-install-tools.
