### ISSUE TITLE
Support PipeWire

### ISSUE THREAD

**Issue by Sunderland93** [ubports/unity8#31]
PipeWire is a new multimedia server, formerly known as "PulseAudio for video". It allows to screen recording/sharing in Wayland (and also remote desktop), and needed for sandboxed apps, e.g. Flatpak. See https://github.com/PipeWire/pipewire/

I also provide a PPA for Ubuntu 18.04 with latest version of PipeWire https://launchpad.net/~samoilov-lex/+archive/ubuntu/pipewire

**Comment by dobey** [comment]
I don't think this belongs in unity8 necessarily. It also doesn't support mir, which is what Unity8 is built on, so I'm not sure it's even usable for us. I'm not sure how much sense it makes either, given the lifecycle management of applications under unity8.

I think this will need a lot more research and thought, to see if any part of pipewire is feasible here. We only really need audio mixing via something like pulseaudio, because system notifications, voice calls, and music playback could all be happening at the same time. This is not the case for video though, as only one application would be active at a time, so multiple video streams shouldn't be playable simultaneously (at least not yet).

**Comment by Sunderland93** [comment]
@dobey Mir become a Wayland compositor, and already purged Mir EGL support, so Unity 8 will no longer support hardware acceleration on newer versions of Mir. PipeWire is needed for apps such as OBS Studio, Simple Screen Recorder, for remote desktop apps (TeamViewer) and sandboxed apps (Flatpak). But maybe support PipeWire - is not Unity 8 problem, but Mir's...

**Comment by dobey** [comment]
Mir supports Wayland clients, but I don't think calling it a Wayland compositor is exactly correct. Unity 8 doesn't currently work on Mir on 18.04 because of the changes there. Piprewire doesn't have anything to do with that, and won't solve the issues there.

As I said, it needs more research as to whether pipewire is useful here or not.

**Comment by UniversalSuperBox** [comment]
Three years later...

I don't think this is an actionable ticket at this point. While PipeWire has developed a lot since this ticket was filed (and is now default for audio in Fedora!), I think that support for it will have separate, focused issues filed in the appropriate repositories.

Until then, I believe it is prudent to close this issue even as it is unsolved.
