### ISSUE TITLE
Login loop

### ISSUE THREAD

**Issue by TheMidnightBear** [ubports/unity8#32]
While the system is updated, it seems any attempts at loging into Unity8 results in a loop that brings me back to the display manager.
Any ideas?

**Comment by UniversalSuperBox** [comment]
I believe this issue was filed regarding a unity8 desktop installer. We are not currently able to offer support for this, and much has changed in the three years between the report and now... We may release more proper desktop installers with our transition of Ubuntu Touch to Ubuntu 20.04, or another distribution may provide proper images with Lomiri.

Either way, I believe this issue should be closed due to its age.
