### ISSUE TITLE
can't install lomiri on ubuntu 16.04 unmet dependencies 

### ISSUE THREAD

**Issue by pixelr0** [ubports/unity8#320]
unmet dependencies 

![fail](https://user-images.githubusercontent.com/333589/87243602-f0ca6080-c43f-11ea-82f9-5ca972465a21.png)

**Comment by mlujan** [comment]
Same results here.

**Comment by mlujan** [comment]
I was able to work around by using 18.04.

**Comment by daleclack** [comment]
Same error

**Comment by ghost** [comment]
same :/

**Comment by Jenga500** [comment]
Same. Only works on 18.04

**Comment by pixelr0** [comment]
> Same. Only works on 18.04

sus!!

**Comment by UniversalSuperBox** [comment]
I believe this issue was filed regarding a unity8 desktop installer. We are not currently able to offer support for this... We may release more proper desktop installers with our transition of Ubuntu Touch to Ubuntu 20.04, or another distribution may provide proper images with Lomiri.

Either way, I believe this issue should be closed since this revision of the project is essentially dropped. Lomiri will still come back to the desktop, but not using unity8-desktop-install-tools.
