### ISSUE TITLE
Installing unity8 on xenial can break system

### ISSUE THREAD

**Issue by Onmp314** [ubports/unity8#345]
I'm submitting a report because, when installing unity8, apt removes unity (7) making the system unusable. I will add that it only happens on Ubuntu 16.04.

Thank you if someone could solve this problem.

**Comment by daleclack** [comment]
I have also experienced it,and I think the reason is lomiri(unity8) and unity7 have dependency conflicts.

**Comment by Onmp314** [comment]
After all, in Ubuntu 16.10 / 17.04 it didn't matter, so what is it?

**Comment by UniversalSuperBox** [comment]
I believe this issue was filed regarding a unity8 desktop installer. We are not currently able to offer support for this... We may release more proper desktop installers with our transition of Ubuntu Touch to Ubuntu 20.04, or another distribution may provide proper images with Lomiri.

Either way, I believe this issue should be closed since this revision of the project is essentially dropped. Lomiri will still come back to the desktop, but not using unity8-desktop-install-tools.
