### ISSUE TITLE
Crashes with "Unknown QPA platform" Ubuntu Mate 16.04 on RPi 3

### ISSUE THREAD

**Issue by SohnyBohny** [ubports/unity8#48]
I'm trying to install unity8 on my `Raspberry Pi 3` running `Ubuntu Mate 16.04`

I've successfully run the install script but can't login ("Failed to start session")

```
$ QML_BAD_GUI_RENDER_LOOP=1 QT_QPA_PLATFORM=mirserver unity8

This application failed to start because it could not find or load the QT platform plugin "mirserver"
in ''''.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, mirserver, ubuntumirclient, vnc, xcb.

Reinstalling the application may fix this problem.
Aborted
```

---

```
$ QML_BAD_GUI_RENDER_LOOP=1 QT_QPA_PLATFORM=mirserver strace -Ff -s 2048 -o unity8-qp
a.log unity8
```
[strace](http://paste.ubuntu.com/p/gMhfS67TfR)

---

```
$ ldd /usr/lib/arm-linux-gnueabihf/qt5/plugins/platforms/libqpa-mirsirver.so

```
[ldd](http://paste.ubuntu.com/p/NppQYtvCCr)

**Comment by human-being-1** [comment]
It might be because all Raspberry Pis use ARM.

**Comment by UniversalSuperBox** [comment]
I believe this issue was filed regarding a unity8 desktop installer. We are not currently able to offer support for this, and much has changed in the three years between the report and now... We may release more proper desktop installers with our transition of Ubuntu Touch to Ubuntu 20.04, or another distribution may provide proper images with Lomiri.

You can try Ubuntu Touch on the Raspberry Pi using our prebuilt images at https://ci.ubports.com/job/rootfs/job/rootfs-rpi/.

Either way, I believe this issue should be closed due to its age.
