### ISSUE TITLE
Xwayland is not usable with Unity 8

### ISSUE THREAD

**Issue by GizmoChicken** [ubports/unity8#56]
This is a known issue.  Work to implement XWayland in Mir is progressing.

I'm reporting this issue _here_ (in the [Unity8 issue tracker](https://github.com/ubports/unity8/issues)) to consolidate related issues that have been previously reported elsewhere (in the wrong issue tracker), including [here](https://github.com/ubports/unity8-desktop-install-tools/issues/32) and [here](https://github.com/ubports/unity8-desktop-install-tools/issues/27).

**Comment by dobey** [comment]
I've changed the title to this, as Xwayland is not actually usable with unity8 at all currently. There seems to be additional work required here, beyond what was/is needed in upstream Mir itself.

**Comment by UniversalSuperBox** [comment]
I believe this issue was filed regarding a unity8 desktop installer. We are not currently able to offer support for this, and much has changed in the years between the report and now... We may release more proper desktop installers with our transition of Ubuntu Touch to Ubuntu 20.04, or another distribution may provide proper images with Lomiri.

Either way, I believe this issue should be closed due to its age.
