### ISSUE TITLE
Provide Unity 8 snap package

### ISSUE THREAD

**Issue by christianrauch** [ubports/unity8#82]
The "Example Mir Desktop Environment" (egmde) is provided as a snap package: https://snapcraft.io/egmde, which makes installation and updates really easy and reduces the risk to break the system with an experimental desktop.

Could the Ubuntu Touch team provide a similar snap package for the Unity 8 desktop?

**Comment by skonsoft** [comment]
Very intersting feature. +1

**Comment by dobey** [comment]
I don't think it makes sense for UBports to do this. At least not until a very long time from now, when Unity 8 actually works reliably on PCs and on the latest versions of Ubuntu. There are not enough people working on the project as it is, and if some were spending time on trying to make this work instead, it would take away from the project as a whole. Plus, without support from Canonical, making Unity 8 work correctly on top of Ubuntu Core would be an extremely daunting task, for the already small team attempting to manage this already humongous project.

Because of this, I'm going to close this for now. If you really want Unity 8 as a snap in the future, the best thing to do now, is to install Unity 8 in a VM or on a spare machine via apt, try to use it as you normally use a PC daily, and report all the issues in various apps and integrations. It needs testing far more than it needs more packages, right now.

**Comment by brlin-tw** [comment]
I'd like to leave a note that [the KDE Plasma Desktop is now packaged as a snap](https://snapcraft.io/blog/kde-apps-at-the-snap-of-your-fingers)
